[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tps-jul21"
version = "0.0.1"
dependencies = [
    "tensorflow",
    "pandas[performance]",
    "statsmodels",
    "matplotlib",
    "seaborn",
    "keras-tuner",
    "scikit-learn"
]